{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "postfix.fullname" . }}
  labels:
    app: {{ template "postfix.name" . }}
    chart: {{ template "postfix.chart" . }}
    release: {{ .Release.Name }}
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - watch
  - list
{{- end }}
