apiVersion: v1
kind: Secret
metadata:
  name: {{ template "postfix.fullname" . }}
  labels:
    app: {{ template "postfix.name" . }}
    chart: {{ template "postfix.chart" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
  tx-smtp-relay-password: {{ .Values.smtp.relayPassword | b64enc }}
